export enum IconName {
  DASHBOARD = 'icon-dashboard',
  PRODUCTS = 'icon-products',
  ORDERS = 'icon-orders',
  USERS = 'icon-users',
  BLOG = 'icon-blog',
  SEARCH = 'icon-search',
  NOTIFICATION = 'icon-notification',
  EDIT = 'icon-edit',
  DELETE = 'icon-delete',
  VIEW = 'icon-view',
  REVENUE = 'icon-revenue',
  PLUS = 'icon-plus',
  CHEVRON_DOWN = 'icon-chevron-down',
  CHEVRON_LEFT = 'icon-chevron-left',
  CHEVRON_RIGHT = 'icon-chevron-right',
  SETTINGS = 'icon-settings',
  PROFILE = 'icon-profile',
  LOGOUT = 'icon-logout',
  INVENTORY = 'icon-inventory',
  CUSTOMER = 'icon-customer',
  USER = 'icon-user',
  LOCK = 'icon-lock',
  EYE = 'icon-eye',
  EYE_OFF = 'icon-eye-off',
  LOADING = 'icon-loading',
}
